### PR TITLE
10 programming buzzwords you need to know

### PR DESCRIPTION
**Pull request by nguyenchr**
@rprieto braindump so far
let me know if you have any _official_ definitions for some of the other words

### CODE REVIEW

**Comment by forkfork** [comment]
@nguyenchr 

Big Data: Recommended for when your companies data grows to the point that programmers have run out of further material for their resume. 

Continuous Delivery: In 1997 scientists discovered that production users don't require a salary, but QA analysts do. This discovery was named 'Continuous Delivery'.

**Comment by forkfork** [comment]
Closures: Javascript tool designed to test how applications handle memory leaks.

**Comment by forkfork** [comment]
NodeJS:  A gang signal used to indicate developer toughness. Gang members will throw a NodeJS gang sign to establish dominance over other developers.

**Comment by rprieto** [comment]
Hahaha Closures :+1:

**Comment by nguyenchr** [comment]
the picture for this article has to be a gang member with a NodeJS tattoo

**Comment by nguyenchr** [comment]
Added all the articles to master, when changing the theme

**Pull request closed without merging**
